version: '3'

tasks:
  go-1-sample:
    cmds:
      - go run one.go ./1-sample.txt
  go-1-puzzle:
    cmds:
      - go run one.go ./1-puzzle.txt
  ts-1-sample:
    cmds:
      - bun one.ts ./1-sample.txt
  ts-1-puzzle:
    cmds:
      - bun one.ts ./1-puzzle.txt
  go-2-sample:
    cmds:
      - go run two.go ./2-sample.txt
  go-2-puzzle:
    cmds:
      - go run two.go ./2-puzzle.txt
  ts-2-sample:
    cmds:
      - bun two.ts ./2-sample.txt
  ts-2-puzzle:
    cmds:
      - bun two.ts ./2-puzzle.txt
